language: python
python: 2.7
env:
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py27
  - TOX_ENV=py27-django
  - TOX_ENV=py35-django
  - TOX_ENV=py35-docs
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
